language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - node
  - lts/*
  - 8
after_success:
  - npx codecov
  - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
